version: '3'

services:
  auth-service:
    image: auth-service
    ports:
      - 3001:3001
  product-service:
    image: product-service
    ports:
      - 3003:3003
  order-service:
    image: order-service
    ports:
      - 3002:3002
  nginx-proxy:
    image: proxy
    depends_on:
      - auth-service
      - product-service
      - order-service
    ports:
      - 80:80


